### ISSUE TITLE
[expansion-panel] doesn't expand 

### ISSUE THREAD

**Issue by andrii-vonage** [Vonage/vivid#1310]
**Describe the bug**
After bumping vwc-expansion-panel from 2.25.5 to 2.
31.0 (by bumping react-vivid from 2.10.10 to 2.10.18) the component stopped to work with the following exception message:
```
Uncaught (in promise) TypeError: this.safeHtml is not a function
    at eval (eval at renderPanelHeader (vwc-expansion-panel.js:88:1), <anonymous>:1:14)
    at VWCExpansionPanel.renderPanelHeader (vwc-expansion-panel.js:88:1)
    at VWCExpansionPanel.render (vwc-expansion-panel.js:93:1)
    at VWCExpansionPanel.update (lit-element.js:236:1)
    at VWCExpansionPanel.performUpdate (updating-element.js:636:1)
    at VWCExpansionPanel._enqueueUpdate (updating-element.js:580:1)
```

**Expected behavior**
Expansion panel should expand

**Screenshots**
https://www.loom.com/share/517fd819348749299ae37ababbd73b2e

**Desktop (please complete the following information):**
 - Device: MacBook M1 Pro
 - OS: macOS Monterey
 - Browser: Chrome
 - Version: Version 102.0.5005.61 (Official Build) (arm64)

**Comment by yinonov** [comment]
@YonatanKra @rachelbt can you please review?

**Comment by YonatanKra** [comment]
@andrii-vonage I am unable to reproduce your issue.
Can you please send a reproduction of this issue?
Either a repository or a [codesandbox](https://codesandbox.io/).
Thanks!
